blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://discord.gg/FCfyBSbCU5
    about: Please ask and answer questions here
  - name: List a token
    url: https://github.com/Earthswap/default-token-list#adding-a-token
    about: Any requests to add a token to Earthswap should go here
